# Configuração principal do EVIL_JWT_FORCE
general:
  timeout: 10
  retries: 3
  threads: 5
  user_agent: "Mozilla/5.0 (EVIL_JWT_FORCE v1.0)"

jwt:
  algorithm: "HS256"
  mode: "bruteforce"
  wordlist_file: "output/wordlist.txt"
  tested_file: "output/wordlist_tested.txt"

aes:
  mode: "CBC"
  key_length: 16
  padding_schemes: ["PKCS7", "ISO10126", "ZeroPadding", "ANSIX923"]

paths:
  report_html: "reports/report.html"
  intercepted_tokens: "output/intercepted_tokens.txt"

proxy:
  use_proxy: true
  rotate_proxies: true
  proxy_list: "config/proxies.txt"

auto_discovery:
  enabled: true
  scan_depth: 3
  timeout_per_request: 5
  common_endpoints:
    - "/api/auth"
    - "/api/login"
    - "/auth/token"
    - "/oauth/token"
    - "/api/v1/auth"
    - "/api/v2/auth"
    - "/auth/jwt"
    - "/login"
    - "/admin/login"
    - "/user/login"
  methods:
    - "GET"
    - "POST"
  headers:
    Content-Type: "application/json"
    Accept: "application/json"
  save_results: true
  output_file: "output/discovered_endpoints.txt"
