# Configuração principal do EVIL_JWT_FORCE (Kali Linux Edition)
general:
  timeout: 15
  retries: 5
  threads: 8
  user_agent: "Mozilla/5.0 (X11; Linux x86_64; rv:124.0) Gecko/20100101 Firefox/124.0"
  log_level: "INFO"
  linux_only: true
  color_output: true
  save_session: true

jwt:
  algorithm: "HS256"
  mode: "bruteforce"
  wordlist_file: "output/wordlist.txt"
  tested_file: "output/wordlist_tested.txt"
  max_token_length: 4096
  min_token_length: 128

aes:
  mode: "CBC"
  key_length: 16
  padding_schemes: ["PKCS7", "ISO10126", "ZeroPadding", "ANSIX923"]
  iv_length: 16

paths:
  report_html: "reports/report.html"
  intercepted_tokens: "output/intercepted_tokens.txt"
  logs_dir: "logs/"
  exports_dir: "exports/"

proxy:
  use_proxy: true
  rotate_proxies: true
  proxy_list: "config/proxies.txt"
  proxy_type: "http"
  max_proxy_failures: 3

auto_discovery:
  enabled: true
  scan_depth: 3
  timeout_per_request: 5
  common_endpoints:
    - "/api/auth"
    - "/api/login"
    - "/auth/token"
    - "/oauth/token"
    - "/api/v1/auth"
    - "/api/v2/auth"
    - "/auth/jwt"
    - "/login"
    - "/admin/login"
    - "/user/login"
  methods:
    - "GET"
    - "POST"
  headers:
    Content-Type: "application/json"
    Accept: "application/json"
  save_results: true
  output_file: "output/discovered_endpoints.txt"